service: guestbook

provider:
  name: kubeless
  hostname: 172.28.225.184.xip.io
  defaultDNSResolution: 'xip.io'
  runtime: python2.7

plugins:
  - serverless-kubeless

functions:
  create:
    handler: handler.create
    environment:
      https_proxy: proxy.esl.cisco.com:80
    events:
      - http:
          path: /create
    
  list:
    handler: handler.list
    environment:
      https_proxy: proxy.esl.cisco.com:80
    events:
      - http:
          path: /list
